name: Deploy

on:  
  push:
    branches:
      - master

jobs:
  testing:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # install & build golang files
    - name: Setup Go
      uses: actions/setup-go@v3.2.0
      with: 
        go-version: "^1.18.3"
        cache: true
    - run: go get
    - name: Generate coverage report
      run: go test  ./... -covermode=atomic -coverprofile=coverage.txt
    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: [testing]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # install nodejs dependencies      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
    # install & build golang files
    - name: Setup Go
      uses: actions/setup-go@v3.2.0
      with: 
        go-version: "^1.18.3"
        cache: true
    - run: go get
    - uses: actions/setup-go@v3.2.0
      with: 
        go-version: "^1.18.3"
    - run: env GOOS=linux go build -ldflags="-s -w" -o bin/main main.go
    - name: Serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
